### ISSUE TITLE
secret.json

### ISSUE THREAD

**Issue by iHarshad** [chrisharrington/node-twitter-sign-in-example#1]
What is the format of secret.json? Is it as shown below? Also do I put the `secret.json` file in the `root` folder of the `lib` folder?

``` json
 {
  "twitter_keys": {
    "consumer_key": "",
    "consumer_secret": "",
    "callbackURL": ""
  }
}
```

**Comment by chrisharrington** [comment]
That's exactly right. I'll update the readme.

**Comment by iHarshad** [comment]
Please update the documentation.

**lib/secret.json**

``` javascript
{
  "twitter": {
    "consumerKey": "",
    "consumerSecret": "",
    "callbackURL": ""
  }
}
```

**Comment by chrisharrington** [comment]
The callback URL should be set as part of your application's domain. Setting it as "/" is misleading.

**Comment by iHarshad** [comment]
Oh yes. Forgot to change that. But the rest of the data in the `lib/secret.json` needs to be updated.

Also on running it `node index` I get the following error:-

```
Cannot GET /
```

I have updated `callbackURL`.

**Comment by chrisharrington** [comment]
The server only exposes two routes: one for retrieving the request token, and another for getting the access token. There's no other routes, and that includes the root.

The rest of the details need to be filled in by the user with their Twitter application details. The consumer key and consumer secret are provided by Twitter when you sign up for a developer application.

All of this is detailed in a blog post I wrote. Take a look.

http://dapperdeveloper.com/2015/09/07/implementing-sign-in-with-twitter-for-node-js/
